const places = [
 {id:'cruise',name:'Grachtenfahrt',category:'Erlebnis',status:'included',coords:[52.3781,4.9005],address:'Prins Hendrikkade 25, Nähe Amsterdam Centraal',duration:'1–1½ Std.',image:'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1200&q=82',short:'Amsterdam vom Wasser aus entdecken – besonders stimmungsvoll am späten Nachmittag.',info:'Die Grachten sind ein UNESCO-Welterbe und erzählen vom Wachstum der Handelsstadt im 17. Jahrhundert. Vom Wasser aus zeigen sich die schmalen Fassaden, Brücken und Hausboote aus einer ganz eigenen Perspektive. Der genaue Anleger hängt vom teilnehmenden City-Card-Anbieter ab; vor der Abfahrt Ticket und Treffpunkt prüfen.',card:'Eine reguläre Fahrt bei einem teilnehmenden Anbieter ist inbegriffen.',official:'https://www.iamsterdam.com/en/tickets/i-amsterdam-city-card'},
 {id:'jordaan',name:'Jordaan & Negen Straatjes',category:'Spaziergang',status:'free',coords:[52.3712,4.8839],address:'Wolvenstraat, 1016 EP Amsterdam',duration:'2–3 Std.',image:'https://images.unsplash.com/photo-1576924542622-772281b13aa8?auto=format&fit=crop&w=1200&q=82',short:'Historische Grachten, unabhängige Läden, Cafés und wunderschöne Wohnhäuser.',info:'Der Jordaan entstand im 17. Jahrhundert als dichtes Viertel für Arbeiter und Handwerker. Heute lohnt es sich, ohne feste Route durch stille Innenhöfe, entlang der Brouwersgracht und durch die neun kleinen Einkaufsstrassen zwischen Singel, Herengracht, Keizersgracht und Prinsengracht zu schlendern.',card:'Frei zugänglich.',official:'https://de9straatjes.nl/en/home'},
 {id:'ndsm',name:'NDSM-Werft',category:'Viertel',status:'free',coords:[52.4010,4.8947],address:'NDSM-Plein, Amsterdam-Noord',duration:'1½–2 Std.',image:'https://images.unsplash.com/photo-1605101100278-5d1deb2b6498?auto=format&fit=crop&w=1200&q=82',short:'Raues Kulturviertel mit Graffiti, Ateliers, Cafés und Industriearchitektur.',info:'Auf dem Areal einer früheren Grosswerft entstand eines der kreativsten Gebiete der Stadt. Riesige Hallen, Kunstprojekte, Flohmärkte und Restaurants stehen nebeneinander. Schon die kostenlose Fährfahrt hinter Amsterdam Centraal gehört zum Erlebnis; an Deck öffnet sich der Blick auf das IJ.',card:'Gelände und GVB-Fähre sind kostenlos.',official:'https://www.ndsm.nl/en/'},
 {id:'straat',name:'STRAAT Museum',category:'Kunst & Erlebnis',status:'included',coords:[52.4008,4.8926],address:'NDSM-Plein 1, 1033 WC Amsterdam',duration:'1½–2 Std.',image:'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=1200&q=82',short:'Monumentale Street Art in einer ehemaligen Schiffbauhalle.',info:'Mehr als hundert grossformatige Arbeiten internationaler Künstlerinnen und Künstler füllen die riesige Lasloods. Viele Werke entstanden direkt vor Ort und zeigen, wie vielfältig Street Art jenseits der Strasse sein kann. Die ungeheizte Industriehalle kann sich je nach Wetter kühl oder warm anfühlen.',card:'Eintritt mit City Card inbegriffen.',official:'https://www.straatmuseum.com/en/plan-your-visit'},
 {id:'fabrique',name:'Fabrique des Lumières',category:'Kunst & Erlebnis',status:'included',coords:[52.3864,4.8692],address:'Pazzanistraat 37, 1014 DB Amsterdam',duration:'1–1½ Std.',image:'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1200&q=82',short:'Immersive Kunst aus Licht, bewegten Bildern und Musik.',info:'In der ehemaligen Gasfabrik des Westergas-Geländes werden Kunstwerke über Wände und Boden einer gewaltigen Halle projiziert. Die Inszenierungen verbinden Malerei, Animation und Musik zu einem körperlichen Raumerlebnis. Das Programm wechselt; aktuelle Ausstellung und Einlasszeiten auf der offiziellen Seite prüfen.',card:'Eintritt mit City Card inbegriffen.',official:'https://www.fabrique-lumieres.com/en/visit'},
 {id:'pijp',name:'De Pijp & Albert-Cuyp-Markt',category:'Markt & Essen',status:'food',coords:[52.3559,4.8955],address:'Albert Cuypstraat, 1073 BD Amsterdam',duration:'2–3 Std.',image:'https://images.unsplash.com/photo-1565881606991-789a8dff9dbb?auto=format&fit=crop&w=1200&q=82',short:'Ein lebendiges Viertel voller Marktstände, kleiner Lokale und Snacks.',info:'De Pijp entwickelte sich im 19. Jahrhundert und ist heute eines der vielfältigsten Quartiere Amsterdams. Auf dem langen Albert-Cuyp-Markt findet ihr Stoffe, Blumen, Käse und Klassiker wie Stroopwafels oder Hering. Für eine ruhigere Pause liegt der Sarphatipark gleich nebenan.',card:'Besuch kostenlos; Einkäufe und Essen nicht enthalten.',official:'https://albertcuyp-markt.amsterdam/'},
 {id:'foodhallen',name:'Foodhallen',category:'Essen',status:'food',coords:[52.3666,4.8680],address:'Bellamyplein 51, 1053 AT Amsterdam',duration:'1–2 Std.',image:'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=82',short:'Viele Küchen unter einem Dach – ideal für ein unkompliziertes Essen zu zweit.',info:'Die Foodhallen befinden sich in den De Hallen, einem umgenutzten Strassenbahndepot aus dem frühen 20. Jahrhundert. Verschiedene Stände servieren kleine Gerichte, sodass ihr teilen und mehrere Küchen probieren könnt. Besonders am Abend kann es lebhaft und gut besucht sein.',card:'Eintritt frei; Speisen und Getränke selbst bezahlen.',official:'https://foodhallen.nl/amsterdam'},
 {id:'wallen',name:'De Wallen & Oude Kerk',category:'Geschichte',status:'included',coords:[52.3744,4.8981],address:'Oudekerksplein 23, 1012 GX Amsterdam',duration:'1½–2 Std.',image:'https://images.unsplash.com/photo-1558551649-e44c8f992010?auto=format&fit=crop&w=1200&q=82',short:'Mittelalterliche Gassen rund um Amsterdams ältestes Gebäude.',info:'Die Oude Kerk wurde um 1300 gegründet und steht mitten im ältesten Teil der Stadt. Rundherum treffen historische Gassen, Chinatown, Cafés und das Rotlichtviertel aufeinander. Am frühen Abend lässt sich die Gegend gut erkunden. Wichtig: Sexarbeiterinnen niemals fotografieren oder filmen.',card:'Viertel frei; Oude Kerk mit City Card inbegriffen.',official:'https://oudekerk.nl/en/'},
 {id:'vondelpark',name:'Vondelpark',category:'Erholung',status:'free',coords:[52.3590,4.8744],address:'Haupteingang Stadhouderskade, Amsterdam',duration:'1–2 Std.',image:'https://images.unsplash.com/photo-1584003564911-a7a321c84e1c?auto=format&fit=crop&w=1200&q=82',short:'Amsterdams grüne Pause für Spaziergänge, Picknick und eine kleine Velorunde.',info:'Der 1865 eröffnete Landschaftspark windet sich mit Teichen, Wiesen und alten Bäumen durch Amsterdam-Zuid. Er ist nicht nur Sehenswürdigkeit, sondern tägliches Wohnzimmer der Stadt: Hier wird gejoggt, musiziert, gepicknickt und Velo gefahren.',card:'Frei zugänglich.',official:'https://www.amsterdam.nl/en/leisure/parks/vondelpark/'},
 {id:'holland',name:'This is Holland',category:'Erlebnis',status:'included',coords:[52.3843,4.9022],address:'Overhoeksplein 51, 1031 KS Amsterdam',duration:'1 Std.',image:'https://images.unsplash.com/photo-1583295125721-766a0088cd3f?auto=format&fit=crop&w=1200&q=82',short:'Ein kurzweiliger 5D-Flug über Landschaften und Wahrzeichen der Niederlande.',info:'Die Attraktion kombiniert eine grosse Kuppelleinwand, bewegliche Sitze sowie Wind- und Dufteffekte. So entsteht der Eindruck eines Flugs über Tulpenfelder, Küste und Städte. Sie liegt direkt gegenüber dem Hauptbahnhof, wenige Minuten von der kostenlosen Buiksloterweg-Fähre entfernt.',card:'Inbegriffen · Reservierung erforderlich.',official:'https://tickets.thisisholland.com/productDetail/48255?lang=en'}
];
const state=JSON.parse(localStorage.getItem('ams-state')||'{"visited":[],"favorites":[],"notes":{},"todos":[]}');let userPos=null,markers=[],filter='all',discoveryIndex=Number(localStorage.getItem('ams-discovery')||0)%places.length;
const $=s=>document.querySelector(s), save=()=>localStorage.setItem('ams-state',JSON.stringify(state));
function haversine(a,b){const R=6371,dLat=(b[0]-a[0])*Math.PI/180,dLon=(b[1]-a[1])*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a[0]*Math.PI/180)*Math.cos(b[0]*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function mapLinks(p){return {apple:`https://maps.apple.com/?daddr=${p.coords.join(',')}&dirflg=w`,google:`https://www.google.com/maps/dir/?api=1&destination=${p.coords.join(',')}&travelmode=walking`}}
function renderDiscovery(){const p=places[discoveryIndex],l=mapLinks(p);$('#discovery').innerHTML=`<div class="discovery-photo" style="background-image:url('${p.image}')"><span>${discoveryIndex+1} / ${places.length}</span></div><div class="discovery-copy"><p class="eyebrow red">UNSER VORSCHLAG</p><h3>${p.name}</h3><p>${p.short}</p><p><strong>${p.duration}</strong> · ${p.category}</p><div class="discovery-actions"><button class="btn secondary" data-show="${p.id}">Mehr erfahren</button><a class="btn skip" href="${l.google}" target="_blank" rel="noopener">Losgehen ↗</a><button class="btn skip" id="skipPlace">Überspringen →</button></div></div>`;$('#skipPlace').onclick=()=>{discoveryIndex=(discoveryIndex+1)%places.length;localStorage.setItem('ams-discovery',discoveryIndex);renderDiscovery()};$('[data-show]').onclick=()=>focusPlace(p.id)}
function badge(p){const label=p.status==='included'?'City Card inklusive':p.status==='free'?'Kostenlos':'Essen & Markt';return `<span class="badge ${p.status==='included'?'card':p.status}">${label}</span>`}
function placeCard(p){const l=mapLinks(p),fav=state.favorites.includes(p.id),done=state.visited.includes(p.id),dist=userPos?`<span>Entfernung<strong>${haversine(userPos,p.coords).toFixed(1)} km</strong></span>`:'';return `<article class="place" id="place-${p.id}"><div class="place-img" style="background-image:url('${p.image}')"><button class="favorite ${fav?'active':''}" data-fav="${p.id}" aria-label="${fav?'Aus Favoriten entfernen':'Zu Favoriten hinzufügen'}">★</button></div><div class="place-body"><div class="place-meta">${badge(p)}<span class="badge">${p.category}</span></div><h3>${p.name}</h3><p>${p.short}</p><button class="more" data-more="${p.id}" aria-expanded="false">Ausführliche Infos lesen ↓</button><div class="long-info" id="more-${p.id}"><p>${p.info}</p><p><strong>City Card:</strong> ${p.card}</p><a href="${p.official}" target="_blank" rel="noopener">Offizielle Informationen ↗</a></div><div class="place-details"><span>Adresse<strong>${p.address}</strong></span><span>Aufenthalt<strong>${p.duration}</strong></span>${dist}</div><div class="place-actions"><button data-map="${p.id}">Auf der Karte</button><a href="${l.apple}" target="_blank" rel="noopener">Apple Karten</a><a href="${l.google}" target="_blank" rel="noopener">Google Maps</a><button class="visited ${done?'done':''}" data-visit="${p.id}">${done?'✓ Besucht':'Als besucht markieren'}</button></div><label class="sr-only" for="note-${p.id}">Notiz zu ${p.name}</label><textarea class="notes" id="note-${p.id}" data-note="${p.id}" placeholder="Unsere Notiz zu diesem Ort …">${state.notes[p.id]||''}</textarea></div></article>`}
function visiblePlaces(){let arr=places.filter(p=>filter==='all'||p.status===filter||filter==='included'&&p.status==='included'||filter==='food'&&p.status==='food');const sort=$('#sort').value;if(sort==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));if(sort==='distance'&&userPos)arr.sort((a,b)=>haversine(userPos,a.coords)-haversine(userPos,b.coords));return arr}
function renderPlaces(){const arr=visiblePlaces();$('#places').innerHTML=arr.map(placeCard).join('');bindCards();updateMarkers(arr)}
function bindCards(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleList('favorites',b.dataset.fav));document.querySelectorAll('[data-visit]').forEach(b=>b.onclick=()=>toggleList('visited',b.dataset.visit));document.querySelectorAll('[data-note]').forEach(n=>n.oninput=()=>{state.notes[n.dataset.note]=n.value;save()});document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>{const x=$(`#more-${b.dataset.more}`),open=x.classList.toggle('open');b.setAttribute('aria-expanded',open);b.textContent=open?'Infos schliessen ↑':'Ausführliche Infos lesen ↓'});document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>focusPlace(b.dataset.map))}
function toggleList(key,id){state[key]=state[key].includes(id)?state[key].filter(x=>x!==id):[...state[key],id];save();renderPlaces();updateProgress()}
function updateProgress(){const n=state.visited.length;$('#progressText').textContent=`${n} von 10 Orten besucht`;$('#progressBar').style.width=`${n*10}%`}
const map=L.map('map',{scrollWheelZoom:false}).setView([52.3738,4.891],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap-Mitwirkende'}).addTo(map);
function color(p){return p.status==='included'?'#b94336':p.status==='food'?'#547a62':'#2d6f91'}function updateMarkers(arr=visiblePlaces()){markers.forEach(m=>map.removeLayer(m));markers=arr.map(p=>{const l=mapLinks(p),m=L.circleMarker(p.coords,{radius:9,color:'#fff',weight:3,fillColor:color(p),fillOpacity:1}).addTo(map).bindPopup(`<strong>${p.name}</strong><p>${p.short}</p><small>${p.card}</small><div class="popup-links"><a href="${l.apple}" target="_blank">Apple</a><a href="${l.google}" target="_blank">Google</a></div>`);m.placeId=p.id;return m})}
function focusPlace(id){const p=places.find(x=>x.id===id);location.hash='karte';map.setView(p.coords,15);setTimeout(()=>markers.find(m=>m.placeId===id)?.openPopup(),350)}
function locate(){const s=$('#geoStatus');if(!navigator.geolocation){s.textContent='Dieser Browser unterstützt keine Standortanzeige.';return}s.textContent='Standort wird einmalig ermittelt …';navigator.geolocation.getCurrentPosition(pos=>{userPos=[pos.coords.latitude,pos.coords.longitude];L.circleMarker(userPos,{radius:9,color:'#fff',weight:3,fillColor:'#e9b44c',fillOpacity:1}).addTo(map).bindPopup('Euer aktueller Standort').openPopup();map.setView(userPos,14);s.textContent='Euer Standort wird auf der Karte angezeigt und nicht gespeichert.';renderPlaces() },()=>s.textContent='Der Standort konnte nicht angezeigt werden. Prüft die Freigabe in den Browser-Einstellungen. Für veröffentlichte Seiten ist HTTPS nötig.',{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function renderTodos(){const ul=$('#todoList');ul.innerHTML=state.todos.map((t,i)=>`<li><input type="checkbox" ${t.done?'checked':''} aria-label="${t.text} erledigt" data-check="${i}"><span>${t.text}</span><button data-delete="${i}" aria-label="${t.text} löschen">×</button></li>`).join('');ul.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{state.todos[x.dataset.check].done=x.checked;save()});ul.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>{state.todos.splice(x.dataset.delete,1);save();renderTodos()})}
$('#todoForm').onsubmit=e=>{e.preventDefault();const i=$('#todoInput');if(i.value.trim())state.todos.push({text:i.value.trim(),done:false});i.value='';save();renderTodos()};
$('#photos').onchange=e=>{[...e.target.files].slice(0,9).forEach(file=>{const r=new FileReader;r.onload=ev=>{const img=new Image;img.src=ev.target.result;img.alt='Lokal ausgewähltes Amsterdam-Foto';$('#photoGrid').append(img)};r.readAsDataURL(file)})};
$('#locate').onclick=locate;$('#nearby').onclick=()=>{if(!userPos){locate();return}filter='all';$('#sort').value='distance';renderPlaces();location.hash='orte'};$('#sort').onchange=renderPlaces;
const categories=['Alle','Erlebnis','Kunst & Erlebnis','Spaziergang','Viertel','Markt & Essen','Essen','Geschichte','Erholung'];$('#filters').innerHTML=categories.map((c,i)=>`<button class="chip ${i===0?'active':''}" data-category="${c}">${c}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=b.dataset.category;$('#places').innerHTML=places.filter(p=>c==='Alle'||p.category===c).map(placeCard).join('');bindCards()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderPlaces()});
$('.nav-toggle').onclick=()=>{const n=$('#navlinks'),open=n.classList.toggle('open');$('.nav-toggle').setAttribute('aria-expanded',open)};$('#reset').onclick=()=>{if(confirm('Wirklich alle Besuche, Favoriten, Notizen und Listeneinträge löschen?')){localStorage.removeItem('ams-state');localStorage.removeItem('ams-discovery');location.reload()}};
const privacy=$('#privacy');if(!localStorage.getItem('ams-privacy'))privacy.showModal();function closePrivacy(){localStorage.setItem('ams-privacy','1');privacy.close()}$('.accept').onclick=closePrivacy;$('.dialog-close').onclick=closePrivacy;
const weatherLabels={0:'klar',1:'überwiegend klar',2:'leicht bewölkt',3:'bewölkt',45:'neblig',48:'neblig',51:'leichter Nieselregen',53:'Nieselregen',55:'starker Nieselregen',61:'leichter Regen',63:'Regen',65:'starker Regen',71:'leichter Schnee',73:'Schnee',75:'starker Schnee',80:'leichte Schauer',81:'Schauer',82:'starke Schauer',95:'Gewitter'};
async function loadWeather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=52.37&longitude=4.90&current=temperature_2m,weather_code&timezone=Europe%2FAmsterdam');if(!r.ok)throw new Error();const d=await r.json(),w=d.current;$('#weather').textContent=`Amsterdam · ${Math.round(w.temperature_2m)} °C · ${weatherLabels[w.weather_code]||'aktuelles Wetter'}`}catch{$('#weather').textContent='Amsterdam-Wetter derzeit nicht verfügbar'}}
$('#date').textContent=new Intl.DateTimeFormat('de-CH',{weekday:'long',day:'numeric',month:'long'}).format(new Date());loadWeather();renderDiscovery();renderPlaces();renderTodos();updateProgress();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
